### ISSUE TITLE
secret engine with description does not get reconciled

### ISSUE THREAD

**Issue by maorfr** [app-sre/vault-manager#15]
The description field does not get automatically applied to an engine, and the integration thinks its never reconciled. this is a newly created secret engine, and not one that is being updated (as tuning is not currently supported).

workarounds: remove description or manually set the description.

example:
```yaml
---
$schema: /vault-config/secret-engine-1.yml

_path: "example/"
type: "kv"
description: "Secrets for Example services."
options:
  _type: "kv"
  version: "2"

```
